emacs-php/php-mode

README.md
php-mode-test.el
tests/issue-200.php

Add test case for issue #200

---

php-mode-test.el
tests/switch-statements.php

- Apply changes of #195
- Refactoring test code
- fix indentation
- better comparison

Improve test

---

php-mode.el

Improve call "php" command

---

README.md

Add MELPA badges

---

README.md
php-mode.el

I checked by `flyspell`.
https://github.com/ejmr/php-mode/pull/260#issuecomment-125859311

Correct misspellings

---

php-mode-test.el

https://github.com/ejmr/php-mode/issues/264#issuecomment-125899343

Improve setting php-mode-test-dir

---

README.md
skeleton/php-array.el

- check-pick #272
- update README(related to #274 and https://github.com/milkypostman/melpa/pull/3106)

Update about php-ext

---

php-mode.el

And update copyright year and last update date.

Fix byte-compile warnings

---

README.md

Add useful PHP package information

---

skeleton/php-math.el

See
- https://github.com/ejmr/php-mode/issues/269#issuecomment-209246817
CC: @mauser2

Remove duplicated skeleton

---

README.md

See
- https://github.com/ejmr/php-mode/issues/285#issuecomment-159884725

Update other package information

---

php-mode-test.el
php-mode.el
tests/issue-305.php

This is related to #305.
CC: @phil-s

Fix invalid highlighting variables which contains 'this' or 'that'

---

php-mode.el

Modify display string in customize interface.
https://www.gnu.org/software/emacs/manual/html_node/elisp/Common-Keywords.html#Common-Keywords

Add defgroup :tag

---

php-mode.el

https://github.com/FriendsOfPHP/PHP-CS-Fixer

Add PHP-CS-Fixer config file to auto-mode-alist

---

README.md
php-mode.el
skeleton/php-current.el

This command was useful to me.  (It's <q>life changing</q>.)  I want to integrate this function in php-mode.

Add command: Insert current class

---

README.md
php-mode-test.el

Fix warning about imenu--make-index-alist not defined

---

php-mode.el

Probably fixes #386 #389
I am planning to add a test so that fracture of font-lock and syntax-table compatibility will not occur. Then we will incorporate improvements #383 by @calbrecht.
This reverts commit 22b5a6aaa91e4f90cf123c2efa19e43d6dafc8df, reversing
changes made to 2fc32548955c0aaf862f578259763149a8cc816e.

Revert "Merge pull request #383 from calbrecht/issue-280"

---

Changelog.md
php-mode.el

close #393 Bump version v1.18.4

Release v1.18.4

---

php-mode.el

Fix missing require imenu and semantic/imenu

---

php-mode.el

change default value of php-do-not-use-semantic-imenu

---

README.md

@hexmode contributed by fix a type in https://github.com/ejmr/php-mode/pull/408

Add Mark A. Hershberger to list of contributors

---

Makefile
php-mode-test.el
php-mode.el
php-project.el

This package is part of php-mode but will be provided as a separate package to interoperate with another major mode in the future.

New php-project.el

---

php-mode-test.el
php-mode.el

It is enough to ensure that this test works without errors.

Add php-mode-debug test

---

.travis.yml
README.md

refs https://github.com/ejmr/php-mode/issues/464

Drop test old emacs

---

php-mode.el

https://twitter.com/official_php/status/1112745899418181632
https://github.com/php/web-php/commit/7075f94093211b56a52a3df28a84de638ae15742
https://github.com/php/web-php/commit/b2b48ca1e053eae9ed0ace036b69ff3ab6926869

Replace https PHP site

---

.travis.yml

Added Emacs 26.2 to Travis CI build matrix

---

CONTRIBUTING.md
README.ja.md
README.md

Add CONTRIBUTING.md

---

php-mode-test.el

Fix macro expansion

---

php-mode.el

Use save-excursion in php-show-arglist

---

php-mode.el

Similar to problem #277, I am receiving the error
```lisp
(error "parse-sexp-propertize-function did not move syntax-propertize--done")
```
due to recursion depth being exceeded.  I am using the current git branch of emacs.  Seems that `re-search` functions can now trigger `syntax-propertize-extend-region-functions` to be called again, which in turn triggers the same call to `php-syntax-propertize-extend-region`.  This stops
recursion when parameters already being processed are passed to `php-syntax-propertize-extend-region`.  This fixes the error and seems to improve handling of large files, though I have not yet profiled it.

prevent recursion in php-syntax-propertize-extend-region

---

php-face.el

Remove `:inherit default` from faces

---

.github/workflows/test.yml
README.ja.md
README.md

[Emacs 27.1 released](https://lists.gnu.org/archive/html/emacs-devel/2020-08/msg00237.html)

Add to support Emacs 27.1

---

.github/workflows/test.yml
README.ja.md
README.md
lisp/php-mode.el

resolve https://github.com/emacs-php/php-mode/issues/592

Make PHP Mode requires Emacs 25.2+

---

lisp/php-mode.el
tests/type-hints.php
tests/type-hints.php.faces

Accepted [PHP RFC: noreturn type](https://wiki.php.net/rfc/noreturn_type), but that type name as `"never"`.

Add never native type for PHP 8.1

---

.github/workflows/test.yml
lisp/php-mode.el

use `php-font-lock-keywords-3` instead of `font-lock-add-keywords`.

Optimize php-mode--string-interpolated-variable-font-lock-find

---

lisp/php-mode.el
tests/8.1/readonly.php
tests/8.1/readonly.php.faces
tests/php-mode-test.el

https://wiki.php.net/rfc/readonly_properties_v2

Add PHP 8.1 readonly keyword

---

CHANGELOG.md
README.ja.md
README.md
lisp/php-align.el
lisp/php-face.el
lisp/php-local-manual.el
lisp/php-mode-debug.el
lisp/php-mode.el
lisp/php-project.el
lisp/php.el

resolve https://github.com/emacs-php/php-mode/issues/700

Bump up version 1.24.1

---

Makefile

Avoid dependencies on packages installed in the user's directory.

Fix Makefile for avoid dependencies on user-installed packages

---

tests/php-mode-test.el

Refactor :magic test

---

CHANGELOG.md
lisp/php-mode.el
tests/indent/issue-623.php
tests/indent/issue-702.php
tests/php-mode-test.el

Fix indentation of expression continuation in arglist

---

lisp/php-mode.el

resolve https://github.com/manateelazycat/lsp-bridge/issues/402
I'm considering setting `$` as a prefix in the syntax table in the future.

Add workaround for acm-backend-tabnine-candidate-expand

---

lisp/php-mode.el

resolve https://github.com/emacs-php/php-mode/issues/747

Fix call to php-mode-debug-reinstall from php-mode

---

CHANGELOG.md
Cask
README.ja.md
README.md
lisp/php-align.el
lisp/php-complete.el
lisp/php-defs.el
lisp/php-face.el
lisp/php-flymake.el
lisp/php-ide-phpactor.el
lisp/php-ide.el
lisp/php-mode-debug.el
lisp/php-mode.el
lisp/php-project.el
lisp/php.el

This released version supports Emacs 29.
Please feel free to [write to disucuss][disscussions-emacs29] if you have problems upgrading to Emacs 29.
[disscussions-emacs29]: https://github.com/emacs-php/php-mode/discussions/751

Release 1.25.0

---

.github/workflows/test.yml

Bump version to avoid: https://github.com/actions/checkout/issues/1448

update github action checkout to v4

---

.github/dependabot.yml

test: Add depend bot

---

CHANGELOG.md
lisp/php-flymake.el

Fixed https://github.com/emacs-php/php-mode/issues/764

Fixed build failure in Emacs on master branch
