emacs-php/php-mode

- php-mode.el
We should not use cl-flet because
- cl-flet is different from flet on Emacs >=24.3
- We should use for defining local function cl-labels or
anonymous function(lambda) + funcall instead of flet
(flet should be used for overriding function temporary,
however we should use cl-letf for this purpose)
- It is unnecessary at all to using cl-flet in php-mode.el now.
> Remove cl-flet

- php-mode-test.el
- php-mode.el
- tests/issue-227.php
This is related to #227.
CC: @jdufresne
> Ignore '=' or '.' if it is inside string or comment

- php-mode.el
> Load cl.el at load time for Emacs 24.4

- php-mode.el
This c-mode issue is still not fixed at Emacs 24.5.
CC: @fxbois
> Fix Emacs 24.5 issue(#238)

- php-mode-test.el
- php-mode.el
- tests/issue-237.php
This is related to #237.
@krzysztof-magosa Could you check [this version](https://raw.githubusercontent.com/ejmr/php-mode/a551255444b48cebb96b96e5273cde4ee86ee803/php-mode.el) ?
> Fix chained method indentation for PSR2 style

- php-mode-test.el
- php-mode.el
- tests/issue-253.php
CC: @redbeardcreator
This is related to #253.
( I suppose this is not smart solution. However I don't know smart answer :-( )
> Workaround 253

- php-mode.el
Because it's default value is 't.
This is related to #270
> Remove font-lock-maximum-decoration setting

- skeleton/php-ext.el
- Set php-ext-path by default
- Fix as Emacs Lisp package
- Delete trailing spaces
This is related to #273
> Improve php-ext package

- README.md
- php-mode.el
- tests/language-constructs.php
I am working on a few patches to add support for some new syntax that is part of PHP 7.0, now that the first alpha is available.  Additional things I want to add before merging this is support for the new `??` operator and group namespace declarations.  I would also appreciate it if anyone double-checks these patches for errors before I merge anything.
> PHP 7.0 Syntax

- README.md
This patch corrects some out-of-date information about the status of PHP 7.
Signed-off-by: Bob W. Hogg <hogg.bob.2@gmail.com>
> [Docs] Update README to note that PHP 7 has been released.

- php-mode.el
We expect that php-syntax-propertize-function is called one time when opening
php file. Before emacs 25, it is called. However Emacs 25 optimizes for reducing
calling syntax-propertize-function and it is not called at opening php file. So
php-mode calls it explicitly in php-mode function.
This is related to #279.
> Workaround for Emacs 25

- php-mode-test.el
- php-mode.el
Emacs 23 is too old and Emacs 25 will be released soon. And it is difficult to compile it on modern environment and it makes maintenance difficult.
This is related to #262,
> Drop Emacs 23 support

- php-mode.el
If there is one `defgroup`, it is used by default.
> Remove needless attributes

- php-mode-test.el
- php-mode.el
- tests/issue-307.php
Since commit 86eab80 php-mode calls php-syntax-propertize-function on
mode activation in emacs 25. This commit wraps the call in the
with-silent-modifications macro so the modification state is retained,
just like how emacs' syntax.el calls syntax-propertize functions.
Resolves issue #307.
> Retain the modification state on mode activation

- php-mode-test.el
In emacs 25, an active major mode will not be active after calling
write-file with a filename that doesn't match the major modes
auto-mode-alist.
Before: https://travis-ci.org/jorissteyn/php-mode/builds/146990813
After: https://travis-ci.org/jorissteyn/php-mode/builds/147005227
> Fix failing test case on emacs 25.1 pretest

- php-mode-test.el
- php-mode.el
- tests/issue-310.php
Work around zealous detection of c member initializers in cc-mode < emacs 25.1. See #310.
>  Fix indentation after function with return type

- php-mode-test.el
- php-mode.el
- tests/issue-314.php
This is related to #314, #315.
Cc: @aaronbieber, @mallt
> Don't move cursor position in php-mode

- php-mode.el
`php-font-lock-keywords-3` definition is different from [`php-create-regexp-for-method`](https://github.com/ejmr/php-mode/blob/10e2e70eaa4b28603935c271c9e2806fd0a6bfc9/php-mode.el#L199-L219) (`\\sw+` and `\\(?:\\sw\\|\\s_\\)`).
> Modify font-lock regexp for function names

- php-mode.el
This is same as 'sh-mode' and 'ruby-mode'.
This is related to #320.
CC: @mallt
> Set '$' as 'prefix class' instead of 'word class'

- skeleton/php-current.el
I'm sorry, `php-namespace-suffix-when-insert`(default: `::`) is correct.
> Fix wrong delimiter

- php-mode-test.el
non-interactive `font-lock-fontify-buffer` is obsoleted in Emacs 25
> Use font-lock-ensure

- README.md
- php-mode-test.el
- php-mode.el
- tests/comments.php
refs #327 
~~I read `cc-font.el`.  I think this change is simple and reliable.~~
I changed the implementation policy and reimplement the mechanism for font-lock.
> Impl PHPDoc font-lock mechanism

- php-mode-test.el
- php-mode.el
- tests/issue-333.php
Fixed #333 
It seems that font-lock freezes Emacs in certain cases by this pattern `"\\(?:\\s-\\|$\\)"`.
> Fixes issue #333

- README.md
- php-mode-test.el
- php-mode.el
- tests/comments.php
Words in a phpDoc comment which start with a keyword are not highlighted correctly. Their keyword prefix is highlighted with `font-lock-type-face`, the rest of the string with `font-lock-doc-face`. Expected highlighting would be `font-lock-doc-face` for the whole word.
This PR fixes this bug.
```php
// Before the fix (^ = font-lock-type-face)
/* @var int internal linter variable */
^^^ ^^^
// After the fix (^ = font-lock-type-face)
/* @var int internal linter variable */
^^^
```
> Fix highlighting of phpdoc type keywords

- php-mode.el
First, `pixiv.net` is better than `www.pixiv.net` because `www.pixiv.net` is not functioning well.
`php-site-url` integrates two variables and keeps compatibility.
> Refactor php-search-web-documentation and php-browse-manual

- php-mode-test.el
- php-mode.el
- tests/doc-comment-return-type.php
This implementation contains unstandardized specification.
But, this form is derived from the [type declarations](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration).
> Add support nullable type annotation

- php-mode-test.el
- php-mode.el
refs #344
By cc-mode restrictions, the following faces do not have mode specific definitions:
- font-lock-comment-face
- font-lock-doc-face
- font-lock-type-face
@Fuco1 Is this change as you expected?
> Add faces for syntax elements

- php-mode.el
This change is for trivial aesthetic.
> Add defgroup :tag and fix comment style

- php-mode-test.el
- php-mode.el
- tests/doc-comment-return-type.php
refs #350 (Cc: @Fuco1)
This PR keeps appearance compatibility.
Users will be able to easily match the color of `$` with variables as you like.
> Add faces for syntax elements #2

- php-mode.el
to be able to select the php-mode code style with the remapped
c-set-style key binding, to have a cleaner code base and reliable
setting of default values over previously set values when changing
the style.
style variables tab-width, fill-column, require-final-newline and
show-trailing-whitespace which are not present in all available
php-mode code styles get their values set from the global default
value on file eval time to the default "php" style.
c-set-style was called twice before this change, now it is called
once, so are the style mode hooks.
> change style initialization to interactive form php-set-style

- .travis.yml
According to
https://github.com/rejeep/evm/blob/72f90d43fcac7861b620f2b6312e44e0604792e2/README.md
the *-bin packages are going to be deprecated because travis is moving
towards a container infrastructure.
Add two more recent emacs versions, 25.2 and 25.3, to the build
matrix.
Replace the ubuntu git-snapshot package with the one provided by evm,
this also ensures the correct version of emacs is running the tests.
Please note, there are failing tests because of known reasons:
emacs 24.3 php-mode-test-issue-357 in this version 'interpreter-mode-alist is not interpreted as regex
emacs git-snapshot: there was a change in the cpp preprocessor macro syntax that breaks single quote string test and indentation.
> adapt new travis environment & more emacs versions

- .travis.yml
refs #380
Suppress test failures in snapshots.
This issue does not affect the released versions, but we will deal with it as soon as possible.
> Add emacs-git-snapshot to travis allow_failures

- php-mode-test.el
- php-mode.el
This PR is based on #372 by @scfc.
refs #378
> Add compatibility shim for interpreter-mode-alist and Emacs < 24.4

- php-mode.el
Remove `\'` and `\"` from syntax table modifications and remove `syntax-propertize-via-font-lock` as it breaks font-locking strings.
Remove `defadvice` around `font-lock-fontify-keywords-region` because it breaks all modes that make use of this function.
Add a new function `php-unescape-identifiers` to `c-lang-defconst` `c-before-font-lock-functions ` to modify syntax table entries for backslashes in identifiers.  As a consequence cc-engine is able
to recognize fully qualified identifiers in the form of `\A\B\C` and also `\A\B::method()`
> fix #280 and cleanup identifiers syntax

- php-mode.el
```
In php-flymake-php-init:
php-mode.el:1589:22:Warning: ‘flymake-init-create-temp-buffer-copy’ is an
obsolete function (as of 26.1); use
‘flymake-proc-init-create-temp-buffer-copy’ instead.
```
Overriding standard functions is not generally a good method.
Use `\'` instead of `$`.
> Trivial refactor flymake

- php-mode.el
In commit [59d07875df](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=59d07875df9d44568d93a7517853e6a5ccaf1e5b) single quotes get a special handling in
`java-mode` and break `php-mode` string font locking.
By removing `c-parse-quotes-before-change` from `c-lang-const`
`c-get-state-before-change-functions`
and `c-parse-quotes-after-change` from `c-lang-const`
`c-before-font-lock-functions` font locking is working again in
git-snapshot.
And since php does not have generics also removing
`c-restore-<>-properties` from `c-lang-const` `c-before-font-lock-functions`
spares some processing time.
> fix #384 single quote string font locking in git-snapshot

- php-mode-test.el
- php-mode.el
- tests/comments.php
These tags is defined in PHPDoc.
https://docs.phpdoc.org/references/phpdoc/tags/throws.html
https://docs.phpdoc.org/references/phpdoc/tags/package.html
However, `@category` and `@subpackage` tag are deprecated.
We do not explicitly support these tags.
> Add phpdoc keyword

- php-mode.el
Probably fixes #386 #389 
This reverts commit 0e87a708fb0cf7bb5ad88baf08bd60e061e8b63c, reversing
changes made to 1b6aeb51a31e9bf1ed8b0593ac909526d42b47a2.
> Revert "Merge pull request #385 from calbrecht/issue-384"

- php-mode.el
This function provides a simple way to search the top directories of PHP project.  It is similar to Projectile, but since it provides only simple functions it does not affect dependencies. However, it is also compatible with Projectile's markers.
> Search project top level

- php-mode.el
Setting php-do-not-use-semantic-imenu to t will force
imenu-create-index-function to be imenu-default-create-index-function
even if semantic-mode is enabled (would be semantic-create-imenu-index
otherwise due to php-mode being a derived mode of c-mode - see
lisp/cedet/semantic/bovine/c.el in emacs sources).
See issue #399
> introduced php-do-not-use-semantic-imenu for disabling semantic-imenu

- php-mode-test.el
- php-mode.el
- tests/arrays.php
`array` was highlighted as a keyword instead of a type hint when the parameter was passed by reference.
> Fix highlighting of array keyword for parameters passed by reference

- README.md
- php-mode.el
- Removed advice "font-lock-fontify-keywords-region" (fixes GitHub Issue: #280)
- Changed syntax-propertize code to work with emacs 25 (fixes GitHub Issue: #371)
- Necessary code changes to replace the advice (font-locking for namespaces)
> fix some font-lock and indentation issues in emacs 25

- php-mode.el
Due to a previous refactoring of the font-locking a bug was introduced
where font-locking was delayed. This happened because
c-before-font-lock-functions did not include the function
c-change-expand-fl-region. This commit adds it back to the cc-mode
variable, so font-locking will not be delayed.
Github Issue: #414
> Fix delayed font-locking issue

- php-mode.el
This command is useful for PHPMode debugging and trouble reporting. In this change, we are aiming exclusively to collect variables. This command was inspired by `web-mode-debug`.
> Add php-mode-debug command

- php-mode-test.el
When `jit-mode` is enabled, face is not set for characters outside the
screen.  Explicitly invalidate `jit-mode` by creating a temporary buffer.
> Fix php-mode-test--buffer-face-list for long code

- php-mode.el
`setq-local` was added in Emacs 24.3.
PHP Mode still keepscompatibility with Emacs 24.1, so we adopted redundant notation.
> Use set and make-local-variable instead setq-local

- php-mode.el
this will make the variable more portable through emacs versions
Reference to Pull Request #416 
Background:
java has to function in the variable we do not want:
- c-parse-quotes-after-change
- c-restore-<>-properties
as those are the only ones making java mode differ from the default
value we use that instead. The default value (which will be used if
no entry is in c-before-font-lock-functions for the used mode) has
changed from emacs 24 to master several times and may change in the
future. So this solution might spare us a few compability commits in
the future.
> set c-before-font-lock-functions to default 't' value to not inherit java's value

- README.ja.md
I would like to improve the quality of the whole documents.
This translation is also for Japanese users, but the biggest motivation is that the current national language of the maintainer (just me) is Japanese.
He (I) is not good at English, so you can build a logical document by working on Japanese. Based on that changes, it will be possible to ask other contributors to write in English.
> Translate README.ja.md

- php-mode.el
refs: #424
The setting of require-final-newline is useful, but in CC-Mode it is not generally overwritten.
These can also be set in [EditorConfig](http://editorconfig.org/) or [`.dir-locals.el`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html).
> Remove set require-final-newline variable from c-add-style clause

- README.ja.md
- php-mode-test.el
- php-mode.el
- php-project.el
This variable is introduced to locally override the customization variable php-mode-coding-style on a project basis.
It is set by the `.dir-locals.el` located in the directory, not the user's own `.emacs` file.
> Add php-project-coding-style variable

- php-project.el
These files are used for PHP initialization processing for dynamic analysis of definitions.
> Add php-project-get-bootstrap-scripts functions

- php-mode.el
refs #89 
This change was introduced in 5a1f99d89ee675aacc4e4868f772e8f78ffaa159, but there is no point in toggling the mode when defining a keymap.
> Remove Subword mode toggle

- php-project.el
Setting these related commands project-local is very important for strict analysis of projects.
>  Add php-project-get-php-executable and php-project-get-phan-executable

- php-mode.el
In the previous implementation, the settings were forcibly overwritten by `php-mode-set-style-delay`.
This change probably resolves #441.
> Fix interference between user hook and c-set-style

- php-mode.el
Statements were not bundled by progn.  This bug was caused by #442.
> [Hotfix] Fix lazy evaluation of php-set-style

- php-mode-test.el
- php-mode.el
refs #398
This is to ensure that variables set by user's hook and file/directory local variables are not overwritten.
> Save the variable and restore it after c-set-style

- php-mode.el
Merge regexp match counts at once.  Although the number of lines is increasing, it is calculated at compile time, so it does not cost anything.
> Refactor regexp pattern of auto-mode-alist

- php-mode.el
refs #69 
This convenient command help organize and gather information useful for php-mode debugging and report.
> Improve php-mode-debug

- php-mode.el
This is a temporary measure because there is a problem with the implementation of `php-mode-set-style-delay`.
> Temporarily disable php-mode-enable-project-coding-style

- php-mode.el
During initialization the variable backup had to be invalidated. Because of that, the default indentation style was adversely affected, so it will be fixed.
> Do not use php-mode-enable-backup-style-variables in initialize

- .travis.yml
- php-mode.el
This is the cause of the error that occurred in Emacs snapshots (later 25) and 26 development versions. We must confess that we did not know how to debug Emacs Lisp and CC Mode.
PHP Mode inherits the properties of java-mode, but Java has no preprocessor, and PHP defined `c-opt-cpp-prefix` for PHP tags.  Therefore, by properly defining `c-anchored-cpp-prefix`, errors are prevented from occurring.
This error was c-macro-is-genuine-p called from c-beginning-of-macro, but this problem is obscured by the huge `condition-case` of `c-syntactic-re-search-forward`.
> Add c-lang-defconst c-anchored-cpp-prefix

- README.ja.md
- README.md
I am no longer an active maintainer of PHP Mode, nor is Syohei Yoshida.
The GitHub issues referenced below provide details about how neither of us
are actively involved in the maintenance of PHP Mode.  Those references
also describe how Usami Kenta is the lead maintianer, which this patch
reflects.
GitHub-Issue: #365
GitHub-Issue: #387
Signed-off-by: Eric James Michael Ritz
> README: Update the list of maintainers to be accurate

- php-mode.el
`declare-function` is a directive that notifies the byte compiler of function definition information.
This suppresses unnecessary error messages during byte compilation.
```
% make
emacs -Q -batch -L . --eval \
"(progn \
(require 'package) \
(package-generate-autoloads \"php-mode\" default-directory))"
Generating autoloads for php-cc-mode.el...
Generating autoloads for php-cc-mode.el...done
Generating autoloads for php-core.el...
Generating autoloads for php-core.el...done
Generating autoloads for php-mode-test.el...
Generating autoloads for php-mode-test.el...done
Generating autoloads for php-mode.el...
Generating autoloads for php-mode.el...done
Generating autoloads for php-project.el...
Generating autoloads for php-project.el...done
Generating autoloads for tiny-init.el...
Generating …
```
> Fix require and supress error messages of byte compile

- php-project.el
This change helps users to identify project-specific directories.
There is usually no risk of conflict between the file name of the marker and the directory name.
In the future, it is possible to control the behavior when the directory name was not the parent directory of the buffer file.
> Make php-project-root accept a string

- Makefile
- etc/git/commit-template.txt
- etc/git/prepare-commit-msg
Git allows users to have "templates" for commits which, when they
exist, automatically fill the user's editor with the template contents
whenever they make a commit.  This does not prevent the user from
further editing the commit message; all it does is pre-populate the
message with pre-written text.
In an effort to help improve the quality of commit messages on PHP
Mode, this patch introduces a commit template along with a Git hook
that, when applied, will automatically fill commit messages with
said template.  The template has comments describing some basic
best-practices for writing Git messages, and has commented-out lines
of some metadata we use, i.e. lines like
GitHub-Issue: #9001
Reviewed-by: Vegeta
This patch updates the Makefile with a new rule, `dev`, that will
install the hook. …
> Add a default Git commit template message

- README.ja.md
- README.md
This patch updates both READMEs with a mention of the official
FeatHub page for the GNU Emacs PHP Suite.  It is highly likely that
users will continue to request features via GitHub itself.  However,
since we discussed using FeatHub (see link below) we need to let users
know that it exists.  If we do not then, obviously, no one will use it.
The changes do not describe exactly *how* users should make requests
through FeatHub because we currently have no defined workflow
involving FeatHub.  In fact, it is not even certain that we will
end up using FeatHub at all; eventually we may very well prefer that
users continue to make feature requests through GitHub's mechanisms.
But we cannot accurately judge the merits of FeatHub if no one is
aware it even exists.
Therefore this patch is a small …
> README: Mention the FeatHub page for feature requests

- README.md
This patch makes use of
https://github.com/sourcerer-io/hall-of-fame
to display a Hall of Fame for the top contributors.  There are two
purposes to this addition:
1. To show gratitude.
2. To hopefully encourage more contributions.
Admittedly there is some concern this may invite developers to
"game" the system, i.e. trying "win" the Hall of Fame by submitting
more patches.  In other words, it could invite a problem of quantity
over quality.  However, I have fath that the emacs-php community is
more mature than that.
This patch does not update the Japanese version of the README since
it explicitly links to the list of contributors in the English version.
Special-thanks: @emacs-php
Special-thanks: Every contributor ever
Signed-off-by: Eric James Michael Ritz <ejmr@no.current.address>
> Add a "Hall of Fame" to the contributors list

- php-mode.el
```
In end of data:
php-mode.el:1864:1:Warning: the function ‘pkg-info-version-info’ is not
known to be defined.
```
> Fix style and suppress warning in compile

- php-mode.el
This change is preparing for massive refactoring in the near future.
I am trying to separate php-mode.el and php.el and have already started working on that.
The purpose of this PR is to clarify variables directly attributable to `php-mode`.
> Add php-mode group and some variables belong to new group

- php-mode.el
fixes #407
This change has BC Break.
This custom variable invalidates `c-mode-hook` and `java-mode-hook`.
There is a discussion as to whether this setting should be enabled by default, but executing hooks in these modes will complicate the configuration for many people.
> Add php-mode-disable-parent-mode-hooks variable

- Cask
- Changelog.md
- php-mode.el
- php-project.el
A minor change from the previous version, but this version has BC brake about `c-mode-hook`.
* Add `php` customize group.
* This group is positioned above `php-mode`.
* This group was originally planned to be included in v1.20.0.
* Add `php-mode-disable-c-mode-hook` custom variable.
* Setting this variable to `nil` will restore the behavior of `c-mode-hook` up to the previous version.
* `php-mode` initialization no longer executes hooks for `c-mode`.
*  If you want to return to the same behavior as the conventional PHP-Mode, set `nil` to `php-mode-disable-c-mode-hook`.
> Release 1.21.0

- Changelog.md
- php-mode-test.el
- php-mode.el
- tests/issue-503.php
> Function php-beginning-of-defun should return non-nil on success

- Cask
- Makefile
- php-mode-debug.el
- php-mode-test.el
- php-mode.el
- php.el
Since `php-mode.el` is extremely large, it is difficult to maintain.  This file contains **features for PHP** and **features for `php-mode`**.  These features are separated by file to clarify their purpose.
> Split php.el and php-mode-debug.el

- php-mode-test.el
refs #524
```diff
diff --git a/php-mode-test.el b/php-mode-test.el
index 98fe95c..0e760be 100644
--- a/php-mode-test.el
+++ b/php-mode-test.el
@@ -930,7 +930,8 @@ style from Drupal."
(ert-deftest php-mode-test-issue-443 ()
"This case allows you to color things that are not authentic PHP tags
(ex.  `<?xml', `<?hh') as false positives."
-  (with-php-mode-test ("issue-443.php" :faces t)))
+  (with-php-mode-test ("issue-443.php"
+                       :faces (if (version<= "27" emacs-version) ".27.faces" t))))
(ert-deftest php-mode-test-type-hints ()
"Test highlighting of type hints and return types."
```
When the condition is met, `issue-443.php` is loaded as "facelist".  `t` is just replaced by `.faces`.
> Enabled to specify suffix of other "facelist" file

- php-face.el
- php-mode.el
- php.el
> Add :tag for customization interface

- php-mode.el
https://wiki.php.net/rfc/null_coalesce_equal_operator
> Add Null Coalescing Assignment Operator (??=) added in PHP 7.4

- php-mode.el
- php.el
refs #538
Suppress warnings when editing from `poly-php-html-mode`.
> Support poly-php-html-mode

- php-mode-test.el
- php-mode.el
- php-project.el
- php.el
refs #362 
closes #483 
This variable is expected to be set by `.dir-locals.el`. You may set the value from the function added to `php-mode-maybe-hook` if it is difficult to set up the [`.dir-locals.el`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html) file in your project.
Set this variable to just `t` or `nil` or [association list](https://www.gnu.org/software/emacs/manual/html_node/elisp/Association-Lists.html)(alist).
If your project does not have an HTML template with a .php extension, just set `nil`. Conversely, if every .php file in your project is an HTML template, you should set `t`.
Suppose that your project has a mix of template `.php` files and script `.php` files.  The settings are as follows if the template file has a specific directory or …
> Add php-mode-maybe and php-project-php-file-as-template

- php-mode.el
Once this variable is defined, you can use forward-page / back-page to move smoothly between the previous and next declaration statements.
> Add page-delimiter custom variable.

- php.el
See https://www.php.net/manual/features.commandline.webserver.php
1. `M-x php-run-builtin-web-server`
2. Input "Document root" or "Router PHP script".
3. Input Port number of web server.
4. Input "Document root" when entered "Router PHP script" in `2`.
> Impl php-run-builtin-web-server command

- php-mode.el
> Add defvar-local php-style-delete-trailing-whitespace

- php.el
* Add php-re-detect-html-tag inline function
* Rename php-re-detect-html-tag to php-re-detect-html-tag-aggressive
* Add save-match-data
> Attenuate detection pattern for php-mode-maybe

- Makefile
- tests/php-mode-test.el
With this change, the autoloads file no longer contains `php-mode-test.el` information.
> Move php-mode-test.el into tests directory

- php.el
Copy class and method name of current position to kill-ring(clipboard).
> Add new command php-copyit-fqsen and fix regexp patterns

- php-mode.el
In practice, `$` is just part of the variable name, which is more advantageous than considering it as “Expression prefixes”.
If you want to be compatible with older syntax tables, add the following code to your own .emacs file (`init.el`):
```el
(with-eval-after-load "php-mode"
(modify-syntax-entry ?$  "'"   php-mode-syntax-table))
```
Past discussions are in the following issues:
* https://github.com/emacs-php/php-mode/issues/320
* https://github.com/emacs-php/php-mode/issues/564
> Modify syntax-entry $ to "_" from "'"

- php-mode.el
This bug was embedded https://github.com/emacs-php/php-mode/pull/377 .
`eq` does not return `T` for comparison of equivalent string objects created separately.
> Fix call run-hooks in set-style

- php-mode.el
resolve https://github.com/emacs-php/php-mode/issues/563
> Fix lineup-cascaded-calls

- php-mode.el
> Make php-set-style display only styles that inherited "php"

- README.ja.md
- README.md
closes https://github.com/emacs-php/php-mode/pull/575
> Add installation from OS packages to README

- php.el
Upcoming versions of emacs have rewritten `rx` and it appears `rx-form` is no longer available (emacs-mirror/emacs@2ed71227c626c6cfdc684948644ccf3d9eaeb15b) 
This PR will replace the two uses of `rx-form`
1. `php-create-regexp-for-method`'s use is replaced with `rx-to-string` which works for supported Emacs before and after the commit referenced above.
2. Use `abbreviate-file-name` instead of the manual regex substitution. I'm not sure if I'm missing an edge case, but it appears this captures the same purpose `rx-form` was being used.
Tests pass except for `php-mode-test-issue-186` but `master` also fails this test.
> Replace uses of `rx-form`

- php-mode.el
Fixes the error, `Undefined style: default`.
> The "default" coding style is actually called "php".

- php-mode.el
> Add php-c-lineup-arglist for unexpected indentation

- php-mode.el
resolve https://github.com/emacs-php/php-mode/issues/586
> Fix issue introduced in #585

- php-mode.el
- php-project.el
If you are developing multiple projects on a daily basis, managing `TAGS` files is cumbersome. This system realizes the application of TAGS files automatically by per project setting (`.dir-locals.el`) or automatic detection mechanism.
The following `.dir-locals.el` code sets the `TAGS` file for each project.
```el
((nil (php-project-root . git)
(php-project-etags-file . (root . "TAGS")))
```
or 
```el
((nil (php-project-root . git)
(php-project-etags-file . t))
```
```el
(custom-set-variables
'(php-project-auto-detect-etags-file tl))
```
```el
(custom-set-variables
'(php-mode-enable-project-local-variable nil))
```
> Add php-project-etags-file and php-project-apply-local-variables

- php.el
This UI can be enhanced by `ido-everywhere`, `ivy-mode`, or `helm-mode`.
> Add php-system-find-php-ini-file and php-ini command

- php-face.el
- php-mode.el
Added faces:
- arithmetic operators
- increment/decrement operators
Added highlighting for:
- logical operators
- arithmetic operators
- comparison operators
- increment/decrement operators
> Add support for multiple operators

- README.md
Please see comments in commit messages, particularly the TODO item in 233715d
> Three minor config points

- Cask
- php-project.el
refs https://github.com/emacs-php/phpactor.el/pull/144
Add `php-project-use-projectile-to-detect-root` custom variable.
If you prefer Projectile, use the Projectile root detection method in preference to php-project's own function.
```el
(projectile-mode)
(with-eval-after-load 'php-project
(custom-set-variables
'(php-project-use-projectile-to-detect-root t)))
```
> Impl interop to Projectile

- php-mode.el
`.php.inc` is file extension for [Rector](https://github.com/rectorphp/rector)'s test code.
`.stub` is file extension for [PHPStan's stub file](https://github.com/phpstan/phpstan-src/tree/master/stubs).
> Add file extension .php.inc and .stub

- tests/issue-186.php
Fix #612
Certainly the indentation is broken, but the use case is not real.
> Ignore Emacs 27 break indentation in case

- php-mode.el
refs https://github.com/emacs-php/php-mode/issues/620
> Add php-mode-disable-c-auto-align-backslashes for disable line continuation

- php-mode.el
- tests/indent/issue-623.php
- tests/php-mode-test.el
> Fix indentation of object operator (->) at the beginning of line

- php-mode.el
- tests/8.0/attribute/function.php
refs https://github.com/emacs-php/php-mode/issues/625
> PHP8 Attributes as new statement without semicolon using vsemi mechanism

- php-mode.el
Fixes https://github.com/emacs-php/php-mode/pull/594/files#diff-6caa62262a5e21bf011a728cd018371fR1547
> Fix regexp where characters following logical negation are not font-locked

- php-mode.el
refs https://github.com/emacs-php/php-mode/issues/631
Accepted: [PHP RFC: Match expression v2](https://wiki.php.net/rfc/match_expression_v2)
> Support PHP 8 match expression

- php-mode.el
- tests/lang/types/keywords.php
- tests/lang/types/keywords.php.faces
`mixed` type declare is added in PHP 8.0.
Accept: [PHP RFC: Mixed Type v2](https://wiki.php.net/rfc/mixed_type_v2)
> Add mixed type

- .dir-locals.el
- Cask
- lisp/php-local-manual.el
- php-align.el
- php-face.el
- php-mode-debug.el
- php-project.el
- php.el
- tests/.dir-locals.el
refs https://github.com/emacs-php/php-mode/issues/638
> Fix Cask and Package-Requires header

- .gitignore
- Keg
refs https://github.com/emacs-php/php-mode/issues/638
[Keg](https://github.com/conao3/keg.el) is a candidate to replace [Cask](https://github.com/cask/cask) in the future, but Cask is not yet removed.
> Add Keg for building

- php-mode.el
refs https://github.com/emacs-php/php-mode/issues/648
If the user leaves this warning unattended, PHP Mode will cause an error and prompt the user for proper operation. I expect this diff to occur immediately after updating Emacs.
> Check CC Mode version when startup php-mode

- lisp/php-mode.el
To support heredoc in this style:
<<< 'HEREDOC'
instead of
<<<'HEREDOC'
> Correct the heredoc regexp.

- .github/workflows/test.yml
- lisp/php-mode.el
- tests/8.1/enum.php
- tests/8.1/enum.php.faces
- tests/php-mode-test.el
resolve https://github.com/emacs-php/php-mode/issues/652
> Impl PHP 8.1 enum syntax

- CHANGELOG.md
- Cask
- lisp/php-align.el
- lisp/php-face.el
- lisp/php-mode-debug.el
- lisp/php-mode.el
- lisp/php-project.el
- lisp/php.el
Thanks @antoineB and @cweiske.
* https://github.com/emacs-php/php-mode/pull/630
* https://github.com/emacs-php/php-mode/pull/632
* https://github.com/emacs-php/php-mode/pull/633
* https://github.com/emacs-php/php-mode/pull/644
* https://github.com/emacs-php/php-mode/pull/651
* https://github.com/emacs-php/php-mode/pull/653
* https://github.com/emacs-php/php-mode/pull/654
> Release v1.24.0

- Makefile
- lisp/php-local-manual.el
- lisp/php-mode.el
- lisp/php.el
I have split the functions that are not related to the processing as major mode into other files.
* Added manual https://github.com/emacs-php/php-mode/wiki/Local-PHP-Manual
Replaces function to search for the keyword at the cursor position.
* **default**: `#'php-search-web-documentation`
```el
(custom-set-variables
'(php-manual-path (expand-file-name "~/local/share/php-manual"))
'(php-search-documentation-function #'php-local-manual-search))
```
No longer refer to the local manual unless you set `php-search-documentation-function`.
> Divide functions for the PHP manual to php.el and php-local-manual.el

- .github/workflows/test.yml
- Cask
- Makefile
External packages depend for testing. The application is not yet dependent on external packages.
> Load cask in testing

- .github/workflows/test.yml
- CHANGELOG.md
- Makefile
- lisp/php-mode.el
- lisp/php.el
- tests/php-mode-test.el
The old list had duplicate items and lacked an index of modern syntax elements.
Modern PHP code focuses on building one class per file. (PSR-4)
We recommend using [bmag/imenu-list](https://github.com/bmag/imenu-list) instead of imenu.
```el
;; For simple display
(custom-set-variables '(php-imenu-generic-expression 'php-imenu-generic-expression-simple))
;; For compatibility
(custom-set-variables '(php-imenu-generic-expression 'php-imenu-generic-expression-legacy))
```
> Improve php-imenu-generic-expression

- lisp/php-mode.el
Remove call `(php-in-string-or-comment-p)`.
> Optimize php-in-string-or-comment-p

- lisp/php-mode.el
Wrongly overwriting `c-looking-at-or-maybe-in-bracelist` definition globally.
> Fix advice buffer local

- lisp/php-mode.el
It was not marked as `lexical-binding` for compatibility with Emacs 23 and earlier. You don't have to keep it today.
This change will slightly improve the performance of closures created with this file, but you may not experience it.
> Add lexical-binding: t

- README.ja.md
- README.md
- Fix a 404 not found link
- OLD: http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/annotations.html
- NEW: https://www.doctrine-project.org/projects/doctrine-annotations/en/latest/index.html
- Use the "https"
- OLD: http://symfony.com/
- NEW: https://symfony.com/
> Fix a 404 link and change to use "https"

- lisp/php-mode.el
```
In php-c-looking-at-or-maybe-in-bracelist:
lisp/php-mode.el:616:74: Warning: Unused lexical argument `containing-sexp'
In php--syntax-propertize-heredoc:
lisp/php-mode.el:967:49: Warning: Unused lexical argument `is-heredoc'
In php-mode--disable-delay-set-style:
lisp/php-mode.el:1078:49: Warning: Unused lexical argument `args'
```
> Suppress warnings unused lexical argument

- README.ja.md
- README.md
PHP Mode is now available from [NonGNU ELPA](https://elpa.nongnu.org/).
[![](https://elpa.nongnu.org/nongnu/php-mode.svg)](https://elpa.nongnu.org/nongnu/php-mode.html) [![](https://elpa.nongnu.org/nongnu-devel/php-mode.svg)](https://elpa.nongnu.org/nongnu-devel/php-mode.html)
PHP once abandoned merging into Emacs, but Emacs 28 makes it easier to install from a package manager.
Please read [Will GNU Emacs Ever Include php mode? · emacs-php/php-mode Wiki](https://github.com/emacs-php/php-mode/wiki/Will-GNU-Emacs-Ever-Include-php-mode%3F)
> Update README about NonGNU ELPA

- AUTHORS.md
- Makefile
- etc/git/AUTHORS2.md.in
- etc/git/former-contributors
Fixed many omissions that occurred when separating the contributor list from the `README.md` to `AUTHORS.md`.
refs https://github.com/emacs-php/php-mode/issues/685, fixes https://github.com/emacs-php/php-mode/pull/607 and closes https://github.com/emacs-php/php-mode/pull/686. Thanks to @Shamar for reporting this issue.
> Properly list the credits of all previous contributors

- lisp/php-mode.el
- lisp/php.el
> Suppress compile-time warnings with long lines

- CHANGELOG.md
- lisp/php-project.el
This function can be used to find the project root when `vc-backends` is disabled.
```el
(add-hook 'project-find-functions #'php-project-project-find-function 0 t)
```
> Add php-project-project-find-function compatible with project-find-functions

- lisp/php.el
Development Emacs generates like the following warnings.
```
php.el:58:12: Warning: defcustom for ‘php-manual-url’ has syntactically odd
type ‘'(choice (const :tag English 'en) (const :tag Brazilian Portuguese
'pt_BR) (const :tag Chinese (Simplified) 'zh) (const :tag French 'fr)
(const :tag German 'de) (const :tag Japanese 'ja) (const :tag Romanian
'ro) (const :tag Russian 'ru) (const :tag Spanish 'es) (const :tag Turkish
'tr) (string :tag PHP manual URL))’
```
> Remove needless quote from choice values

- lisp/php-mode.el
refs https://github.com/emacs-php/php-mode/issues/702, fixed https://github.com/emacs-php/php-mode/pull/519/commits/8a437100f6b2bbb84bc8aee8577ba302922d2af1
> Remove (c-lang-defconst c-opt-<>-sexp-key)

- lisp/php-mode.el
ref: https://phpstan.org/blog/phpstan-1-9-0-with-phpdoc-asserts-list-type#describe-type-of-current-object-after-calling-a-method
> Add @phpstan-self-out and @phpstan-this-out keywords

- CHANGELOG.md
- Makefile
- lisp/php-flymake.el
- lisp/php-mode.el
- lisp/php.el
Fix [Flymake](https://www.gnu.org/software/emacs/manual/html_node/emacs/Flymake.html) compatibility for all environments. A new feature, `php-flymake`, avoids creating temporary files by using STDIN.
Flymake functions compatible with `flymake-diagnostic-functions`.
As default Flymake implementation in PHP Mode, it is controlled by `php-mode-replace-flymake-diag-function` variable described below.
**default**: `#'php-flymake`
Specify a Flymake function to replace from PHP Mode. Set `nil` to stop replacement.
> New feature: php-flymake

- CHANGELOG.md
- lisp/php-mode-debug.el
- lisp/php-mode.el
PHP Mode depends on Cc Mode functions and macros, so in general byte-compiled code must be recompiled when Cc Mode version changes. This function prompts the user to reinstall PHP Mode.
Generally, the only people who need to use this command are those who have installed another version of Emacs themselves, or who have compiled their own Emacs HEAD.
If you have installed PHP Mode via a package manager, it would be wiser to update via that mechanism rather than this function.
> Add php-mode-debug-reinstall

- CHANGELOG.md
- Cask
- Makefile
- lisp/php-format.el
> **Note**
> This is an experimental feature.  We are looking for your feedback to improve the usability.
This feature is for execute PHP code formatting tools.
- [Easy Coding Standard](https://github.com/easy-coding-standard/easy-coding-standard) (ecs)
- [PHP-CS-Fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer) (php-cs-fixer)
- [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) (phpcbf)
It supports both per-project and globally installed ones.
Add following line to setup function for php-mode.
```el
(php-format-auto-mode +1)
```
These variables can be set either by dir-locals.el or by custom-set-variable.
- `php-format-auto-mode-hook-depth`
- `php-format-command`
- `php-format-command-dir`
- `php-format-default-idle-time`
- `php-format-result-display-method-alist`
How …
> New feature: php-format.el

- CHANGELOG.md
- lisp/php-mode.el
- tests/indent/issue-726.php
- tests/php-mode-test.el
> Fix #726 indentation

- lisp/php-format.el
If the buffer was modified between the time the file was saved and the timer fired, it makes sense to cancel the formatter invocation to avoid conflicting editor and formatter states.
To make sure your code is formatted by `php-format-auto-mode`, save and take a break from your keyboard.
fixes https://github.com/emacs-php/php-mode/pull/731
> Add php-format-disable-async-format-buffer-has-modified

- lisp/php-mode.el
Apply part of the patch received from [Stefan Monnier](https://www.iro.umontreal.ca/~monnier/). This PR contains changes that do not affect behavior.
> Apply Stefan Monnier's patch (1)

- lisp/php-mode.el
continuation of https://github.com/emacs-php/php-mode/pull/737
> Apply Stefan Monnier's patch (2)

- lisp/php-mode.el
continuation of https://github.com/emacs-php/php-mode/pull/739
> Apply Stefan Monnier's patch (3)

- lisp/php-mode.el
Resolves: https://github.com/emacs-php/php-mode/issues/745
> Disable php-mode-lineup-cascaded-calls for PEAR style

- .github/workflows/test.yml
- CHANGELOG.md
- README.ja.md
- README.md
- tests/php-mode-test.el
- tests/type-hints.php.29.faces
https://lists.gnu.org/archive/html/emacs-devel/2023-07/msg00704.html
> Support Emacs 29.1

- .github/workflows/test.yml
> **Note**
>  This released version supports Emacs 29. <br />Please feel free to [write to disucuss][disscussions-emacs29] if you have problems upgrading to Emacs 29.
[disscussions-emacs29]: https://github.com/emacs-php/php-mode/discussions/751
> Add Emacs 29.1 to CI

- CHANGELOG.md
- lisp/php-project.el
This variable and function were merged in #436.
[Phan](https://github.com/phan/phan) was the only working PHP static analyzer back in 2018, but Phan is probably not called via this variable today.
Don't worry, PHPDoc will still support highlighting `@phan-` prefixed tags.
> Remove Phan-specific features from php-project.el

- lisp/php.el
Uses quote and adds missing `__DIR__`
> php-magical-constant: align implementation with php-ts-mode

- AUTHORS.md
- lisp/php-mode.el
Adds a imenu styling similar to consult imenu for emacs lisp.
> add support for consult imenu

- lisp/php-face.el
- lisp/php-format.el
Fixes:
```
lisp/php-face.el:128:2: Warning: custom-declare-face `php-paamayim-nekudotayim' docstring wider than 80 characters
lisp/php-face.el:211:2: Warning: custom-declare-face `php-class-declaration-spec' docstring wider than 80 characters
lisp/php-face.el:241:2: Warning: custom-declare-face `php-control-structure' docstring wider than 80 characters
```
and
```
lisp/php-format.el:97:12: Warning: defcustom for ‘php-format-command’ has syntactically odd type ‘'(choice (const :tag Disabled reformat codes nil) (const :tag Auto 'auto) (const :tag Easy Coding Standard 'ecs) (const :tag PHP-CS-Fixer 'php-cs-fixer) (const :tag PHP Code Beautifier and Fixer 'phpcbf) (repeat :tag Command and arguments string))’
```
> fix byte compilation warnings

- .github/workflows/test.yml
- .gitignore
- Eask
- Makefile
- tests/php-mode-test.el
> ci: Build with Eask 

- lisp/php-flymake.el
- lisp/php-mode.el
The following changes have been commited to the Emacs master branch.
https://github.com/emacs-mirror/emacs/commit/81c6569e654966c63f208013a4faf7ddb2a5d933
The places where `flymake-proc` is used within php-mode are as follows.
```console
$ git grep "flymake-proc" .
lisp/php-flymake.el:  (setq-local flymake-proc-allowed-file-name-masks nil)
lisp/php-mode.el:   (unless (boundp 'flymake-proc-allowed-file-name-masks)
$
```
https://github.com/emacs-php/php-mode/commit/7e93315a8e28a26f5f8398ecd519beff00ca9a82 I added (require 'flymake-proc) in this commit.
> Add (require 'flymake-proc)

- CHANGELOG.md
- lisp/php.el
[topsy.el](https://github.com/alphapapa/topsy.el) works without any configuration, but this configuration allows you to view classes as well as just functions.
> Add php-topsy-beginning-of-defun-with-class for Topsy

- CHANGELOG.md
- lisp/php-mode.el
- lisp/php.el
Add `php-base-mode` like `js-base-mode` for enhanced interoperability with [`php-ts-mode`](https://github.com/emacs-php/php-ts-mode).
You can use `php-base-mode-hook` for common configuration of `php-mode` and `php-ts-mode`.
closes https://github.com/emacs-php/php-mode/pull/678
> Make php-mode inherit from php-base-mode instead of c-mode

- CHANGELOG.md
- lisp/php-mode.el
refs #772, `php-mode` no longer inherits `c-mode`, so this variable won't work.
> Remove php-mode-disable-c-mode-hook custom variable

- CHANGELOG.md
- lisp/php-mode.el
- tests/indent/issue-227.php
- tests/indent/issue-774.php
- tests/php-mode-test.el
No longer overindent it by default, since we don't see any mention in the coding style that it should hang `.`. 
closes #227, #774 and #745, refs #229.
> [!NOTE]
> If you have any feedback on [PEAR style](https://pear.php.net/manual/en/standards.php), please let us know in [the discussion #776](https://github.com/emacs-php/php-mode/discussions/776).
> Modify over-indentation for PEAR style

- CHANGELOG.md
- lisp/php-mode.el
resolve https://github.com/emacs-php/php-mode/issues/785
This issue was first introduced in #316 as a workaround for a problem with Emacs 25 not coloring properly. This approach was disadvantageous for large files, and although performance was improved in #531, we often suffered from flickering.
The previous approach of reapplying `php-syntax-propertize-function` was messing with Emacs' internal state, so resetting it seems to fix a lot of the issues.
refs https://github.com/emacs-php/php-mode/issues/491, https://github.com/emacs-php/php-mode/pull/308
> Just call syntax-ppss-flush-cache instead of an explicit property.

- .github/workflows/test.yml
- lisp/php-mode.el
> [!NOTE]
> The last PHP Mode that supports Emacs 26 is [`v1.26`](https://github.com/emacs-php/php-mode/releases/tag/v1.26.1).
> Please read #464 and #771 for our support policy.
> Drop support for Emacs 26

- lisp/php-mode.el
If the first pair of searches found a heredoc which spanned the entire region, don't perform the second pair of searches, as we already know the new region bounds.
If we do need the second pair of searches, bound the backwards search at the original region START position.
> Improve php-syntax-propertize-extend-region efficiency

- lisp/php-ide-phpactor.el
- lisp/php-mode.el
- lisp/php.el
> Fix Emacs 30 byte-compile errors
